#!/bin/bash
# Copyright (c) 2010 Tomasz Dlugosz <tomek3d@gmail.com> 
# distributed under the terms of the GNU General Public License v3

function pokaz_nazwy() {
	linia=`tail -n $((ile_pozycji-$3+1)) < $2 | head -n 1`
	ile_szukanego=`echo $linia | cut -f 2 -d '|'`

	if [ $pozycja -ge 2 ]; then
		towar_info $((pozycja-1)) $2
	fi 
	echo -e "Poz. ${pozycja}: BRAK TOWARU! - \t$ile_szukanego x $1"

	pokaz_nastepny=1
}

function towar_info() {
	echo -n "Poz. ${1}: "
	linia=`tail -n $((ile_pozycji-$1+1)) < $2 | head -n 1`
	ile=`echo $linia | cut -f 2 -d '|'`
	kod=`echo $linia | cut -f 1 -d '|'`
	nazwa=`chval 6 rq -fbar_kod_tow=${kod} | cut -f 7 -d '|'`
	if [ -n "$nazwa" ]; then
		echo -e "\t\t$ile $nazwa $kod"
		if [ "$pokaz_nastepny" -gt 0 ]; then 
			pokaz_nastepny=$(($pokaz_nastepny-1))
			if [ "$pokaz_nastepny" -eq 0 ]; then 
				echo
			fi
		fi
	else
		id_tow=`chval 33 rq -fbar_kod_tow=${kod} | cut -f 3 -d '|'`
		id_tow=`echo $id_tow | sed -e 's/^0*//'`
		nazwa=`chval 6 rq -fid_tow=${id_tow} | cut -f 7 -d '|'`
		if [ -n "$nazwa" ]; then
			echo -e "\t\t$ile $nazwa $kod"
			if [ "$pokaz_nastepny" -gt 0 ]; then 
				pokaz_nastepny=$(($pokaz_nastepny-1))
				if [ "$pokaz_nastepny" -eq 0 ]; then 
					echo
				fi
			fi
		else
			echo -e "BRAK TOWARU! - \t$ile x $kod"
		fi
	fi
}

if [ $# -ne 1 ]; then
	echo "podaj nazwe pliku z backupem"
	exit
fi

if [ -f $1 ]; then 
	echo -e "Wczytuje plik $1 \n"
else 
	echo nie ma takiego pliku!
	exit
fi

pozycja=0
pokaz_nastepny=0
ile_pozycji=`wc -l < $1`
while read i; do
	pozycja=$((pozycja+1))
	n=`echo $i | cut -f 1 -d '|'` 
	if [ "$pokaz_nastepny" -gt 0 ]; then 
		towar_info $pozycja $1
	elif [ `chval 6 rq -fbar_kod_tow=${n} | wc -l` -lt 1 ] && [ `chval 33 rq -fbar_kod_tow=${n} | wc -l` -lt 1 ]; then
		pokaz_nazwy $n $1 $pozycja 
	fi
done < $1
